// Generated by tools/embed-fonts.mjs from figlet 1.11.4. Do not edit; edit the tool and rerun it.
// Each entry: the font's FLF text, its family, whether it is blessed, its row count, and its columns per capital letter (the alphabet's width over 26).
import f_ANSI_Shadow from 'figlet/fonts/ANSI Shadow';
import f_ANSI_Regular from 'figlet/fonts/ANSI Regular';
import f_Delta_Corps_Priest_1 from 'figlet/fonts/Delta Corps Priest 1';
import f_DOS_Rebel from 'figlet/fonts/DOS Rebel';
import f_Electronic from 'figlet/fonts/Electronic';
import f_Pagga from 'figlet/fonts/Pagga';
import f_Calvin_S from 'figlet/fonts/Calvin S';
import f_Standard from 'figlet/fonts/Standard';
import f_Small from 'figlet/fonts/Small';
import f_Big from 'figlet/fonts/Big';
import f_Slant from 'figlet/fonts/Slant';
import f_Small_Slant from 'figlet/fonts/Small Slant';
import f_Mini from 'figlet/fonts/Mini';
import f_Doom from 'figlet/fonts/Doom';
import f_Ogre from 'figlet/fonts/Ogre';
import f_Rectangles from 'figlet/fonts/Rectangles';
import f_Chunky from 'figlet/fonts/Chunky';
import f_Thick from 'figlet/fonts/Thick';
import f_Cybermedium from 'figlet/fonts/Cybermedium';
import f_Speed from 'figlet/fonts/Speed';
import f_Small_Caps from 'figlet/fonts/Small Caps';
import f_Shadow from 'figlet/fonts/Shadow';
import f_Roman from 'figlet/fonts/Roman';
import f_Georgia11 from 'figlet/fonts/Georgia11';
import f_Colossal from 'figlet/fonts/Colossal';
import f_Alligator2 from 'figlet/fonts/Alligator2';
import f_Fraktur from 'figlet/fonts/Fraktur';
import f_Broadway from 'figlet/fonts/Broadway';
import f_Script from 'figlet/fonts/Script';
import f_Small_Script from 'figlet/fonts/Small Script';
import f_SL_Script from 'figlet/fonts/SL Script';
import f_Cursive from 'figlet/fonts/Cursive';
import f_Graffiti from 'figlet/fonts/Graffiti';
import f_Larry_3D from 'figlet/fonts/Larry 3D';
import f_3D_ASCII from 'figlet/fonts/3D-ASCII';
import f_Henry_3D from 'figlet/fonts/Henry 3D';
import f_Isometric1 from 'figlet/fonts/Isometric1';
import f_Slant_Relief from 'figlet/fonts/Slant Relief';
import f_Big_Money_ne from 'figlet/fonts/Big Money-ne';
import f_Ghost from 'figlet/fonts/Ghost';
import f_Poison from 'figlet/fonts/Poison';
import f_LCD from 'figlet/fonts/LCD';
import f_Digital from 'figlet/fonts/Digital';
import f_Dot_Matrix from 'figlet/fonts/Dot Matrix';
import f_Keyboard from 'figlet/fonts/Keyboard';
import f_Star_Wars from 'figlet/fonts/Star Wars';
import f_Bloody from 'figlet/fonts/Bloody';
import f_Fire_Font_k from 'figlet/fonts/Fire Font-k';
import f_Varsity from 'figlet/fonts/Varsity';
import f_Sub_Zero from 'figlet/fonts/Sub-Zero';

export const FONTS = {
  "ANSI Shadow": { data: f_ANSI_Shadow, family: 'block', blessed: true, rows: 6, perLetter: 8.3 },
  "ANSI Regular": { data: f_ANSI_Regular, family: 'block', blessed: true, rows: 6, perLetter: 8.3 },
  "Delta Corps Priest 1": { data: f_Delta_Corps_Priest_1, family: 'block', blessed: true, rows: 9, perLetter: 11.8 },
  "DOS Rebel": { data: f_DOS_Rebel, family: 'block', blessed: true, rows: 8, perLetter: 13.0 },
  "Electronic": { data: f_Electronic, family: 'block', blessed: true, rows: 11, perLetter: 13.0 },
  "Pagga": { data: f_Pagga, family: 'block', blessed: true, rows: 3, perLetter: 4.0 },
  "Calvin S": { data: f_Calvin_S, family: 'box', blessed: true, rows: 3, perLetter: 3.0 },
  "Standard": { data: f_Standard, family: 'sans', blessed: true, rows: 5, perLetter: 6.3 },
  "Small": { data: f_Small, family: 'sans', blessed: true, rows: 4, perLetter: 5.3 },
  "Big": { data: f_Big, family: 'sans', blessed: false, rows: 6, perLetter: 7.3 },
  "Slant": { data: f_Slant, family: 'sans', blessed: false, rows: 5, perLetter: 6.3 },
  "Small Slant": { data: f_Small_Slant, family: 'sans', blessed: false, rows: 4, perLetter: 5.5 },
  "Mini": { data: f_Mini, family: 'sans', blessed: false, rows: 3, perLetter: 3.9 },
  "Doom": { data: f_Doom, family: 'sans', blessed: false, rows: 6, perLetter: 6.5 },
  "Ogre": { data: f_Ogre, family: 'sans', blessed: false, rows: 5, perLetter: 5.9 },
  "Rectangles": { data: f_Rectangles, family: 'sans', blessed: false, rows: 5, perLetter: 6.0 },
  "Chunky": { data: f_Chunky, family: 'sans', blessed: false, rows: 4, perLetter: 7.8 },
  "Thick": { data: f_Thick, family: 'sans', blessed: false, rows: 4, perLetter: 6.6 },
  "Cybermedium": { data: f_Cybermedium, family: 'sans', blessed: false, rows: 3, perLetter: 4.8 },
  "Speed": { data: f_Speed, family: 'sans', blessed: false, rows: 5, perLetter: 7.8 },
  "Small Caps": { data: f_Small_Caps, family: 'sans', blessed: false, rows: 4, perLetter: 6.8 },
  "Shadow": { data: f_Shadow, family: 'sans', blessed: false, rows: 4, perLetter: 7.3 },
  "Roman": { data: f_Roman, family: 'serif', blessed: false, rows: 8, perLetter: 13.8 },
  "Georgia11": { data: f_Georgia11, family: 'serif', blessed: false, rows: 9, perLetter: 12.1 },
  "Colossal": { data: f_Colossal, family: 'serif', blessed: false, rows: 11, perLetter: 11.2 },
  "Alligator2": { data: f_Alligator2, family: 'serif', blessed: false, rows: 7, perLetter: 11.3 },
  "Fraktur": { data: f_Fraktur, family: 'serif', blessed: false, rows: 15, perLetter: 20.2 },
  "Broadway": { data: f_Broadway, family: 'serif', blessed: false, rows: 11, perLetter: 18.0 },
  "Script": { data: f_Script, family: 'script', blessed: false, rows: 7, perLetter: 6.7 },
  "Small Script": { data: f_Small_Script, family: 'script', blessed: false, rows: 5, perLetter: 5.5 },
  "SL Script": { data: f_SL_Script, family: 'script', blessed: false, rows: 6, perLetter: 5.6 },
  "Cursive": { data: f_Cursive, family: 'script', blessed: false, rows: 6, perLetter: 5.6 },
  "Graffiti": { data: f_Graffiti, family: 'script', blessed: false, rows: 6, perLetter: 9.6 },
  "Larry 3D": { data: f_Larry_3D, family: '3d', blessed: false, rows: 7, perLetter: 8.8 },
  "3D-ASCII": { data: f_3D_ASCII, family: '3d', blessed: false, rows: 8, perLetter: 10.8 },
  "Henry 3D": { data: f_Henry_3D, family: '3d', blessed: false, rows: 8, perLetter: 9.2 },
  "Isometric1": { data: f_Isometric1, family: '3d', blessed: false, rows: 11, perLetter: 13.7 },
  "Slant Relief": { data: f_Slant_Relief, family: '3d', blessed: false, rows: 9, perLetter: 18.6 },
  "Big Money-ne": { data: f_Big_Money_ne, family: '3d', blessed: false, rows: 9, perLetter: 10.2 },
  "Ghost": { data: f_Ghost, family: '3d', blessed: false, rows: 9, perLetter: 10.6 },
  "Poison": { data: f_Poison, family: '3d', blessed: false, rows: 10, perLetter: 10.0 },
  "LCD": { data: f_LCD, family: 'retro', blessed: false, rows: 5, perLetter: 5.9 },
  "Digital": { data: f_Digital, family: 'retro', blessed: false, rows: 3, perLetter: 2.1 },
  "Dot Matrix": { data: f_Dot_Matrix, family: 'retro', blessed: false, rows: 8, perLetter: 14.9 },
  "Keyboard": { data: f_Keyboard, family: 'retro', blessed: false, rows: 7, perLetter: 8.0 },
  "Star Wars": { data: f_Star_Wars, family: 'decorative', blessed: false, rows: 6, perLetter: 11.0 },
  "Bloody": { data: f_Bloody, family: 'decorative', blessed: false, rows: 10, perLetter: 8.5 },
  "Fire Font-k": { data: f_Fire_Font_k, family: 'decorative', blessed: false, rows: 8, perLetter: 6.5 },
  "Varsity": { data: f_Varsity, family: 'decorative', blessed: false, rows: 6, perLetter: 11.0 },
  "Sub-Zero": { data: f_Sub_Zero, family: 'decorative', blessed: false, rows: 5, perLetter: 10.7 },
};
