// asciify core: pure functions with no Node imports, so the same code runs in Node, a browser, and on Vercel.
export { measure } from './measure.js';
export { check, BANDS } from './check.js';
export { halfblocksToPixels, components, erode } from './pixels.js';
export { RAMPS } from './ramps.js';
export { contrast, luminance, parseHex } from './contrast.js';
export { FONTS } from './fonts.js';
export { registerFont, hasFont, fontInfo, fontNames, families, renderLine, fontGlyphs } from './figlet.js';
export { wordmark, previews, render, alt } from './wordmark.js';
export { interpret } from './styles.js';
export { parseBitmap, toGrid, renderHalfblocks, scaleBitmap, bitmapMap } from './bitmap.js';
export * as geometry from './geometry.js';
export { renderScene } from './geometry.js';
export { decodePNG, encodePNG } from './png.js';
export { decodeBMP } from './bmp.js';
export { grayscale, resample, resampleRGB, otsu, classify, despeckle, imageToBitmap, imageToSketch } from './image.js';
export { parseColor, toHex, mix, gradient, fitContrast } from './color.js';
export { PRESETS, BACKGROUNDS, makeColorway, fitColorway, colorwayNames, preset } from './colorways.js';
export { RESET, nearest256, fg, bg, glyphClass, regionKeys, regionPainter, colorizeText, colorizeBitmap, colorizeSketch, stripAnsi } from './ansi.js';
export { htmlText, htmlBitmap, htmlSketch } from './html.js';
export { paintCell } from './cells.js';
export { parseFont, rasterizeText, fillPolygons, paintGlyph, glyphPathData, cellMetrics } from './fontraster.js';
export { rasterizeGrid, imageFromGrid, imageFromBitmap, imageFromFrame, svgFromBitmap, svgFromGrid } from './raster.js';
export { frameFromText, frameToText, cloneFrame, blankFrame, paintFrame, frameFromBitmap, ansiFrame, htmlFrame, clipToJSON, clipFromJSON } from './frames.js';
export { EFFECTS, effectNames, rng } from './effects.js';
export { animate, parseEffects } from './animate.js';
export { encodeGIF, inspectGIF } from './gif.js';
