// Generates ../fonts.js: a static import per embedded font plus its family, blessing, and measured size.
// Run from the repository root: node packages/core/tools/embed-fonts.mjs
import { writeFileSync, statSync } from 'node:fs';
import figlet from 'figlet/browser';

const FAMILIES = {
  block: ['ANSI Shadow', 'ANSI Regular', 'Delta Corps Priest 1', 'DOS Rebel', 'Electronic', 'Pagga'],
  box: ['Calvin S'],
  sans: ['Standard', 'Small', 'Big', 'Slant', 'Small Slant', 'Mini', 'Doom', 'Ogre', 'Rectangles', 'Chunky', 'Thick', 'Cybermedium', 'Speed', 'Small Caps', 'Shadow'],
  serif: ['Roman', 'Georgia11', 'Colossal', 'Alligator2', 'Fraktur', 'Broadway'],
  script: ['Script', 'Small Script', 'SL Script', 'Cursive', 'Graffiti'],
  '3d': ['Larry 3D', '3D-ASCII', 'Henry 3D', 'Isometric1', 'Slant Relief', 'Big Money-ne', 'Ghost', 'Poison'],
  retro: ['LCD', 'Digital', 'Dot Matrix', 'Keyboard'],
  decorative: ['Star Wars', 'Bloody', 'Fire Font-k', 'Varsity', 'Sub-Zero'],
};
const BLESSED = new Set(['ANSI Shadow', 'ANSI Regular', 'Delta Corps Priest 1', 'DOS Rebel', 'Electronic', 'Pagga', 'Calvin S', 'Standard', 'Small']);
const ALPHA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

const trimRows = (out) => {
  const lines = out.split('\n').map((l) => l.replace(/\s+$/, ''));
  while (lines.length && lines[lines.length - 1] === '') lines.pop();
  while (lines.length && lines[0] === '') lines.shift();
  return lines;
};

const ident = (name) => 'f_' + name.replace(/[^A-Za-z0-9]/g, '_');
const imports = [], entries = [];
let total = 0;
for (const [family, names] of Object.entries(FAMILIES)) {
  for (const name of names) {
    const modPath = new URL(`../../../node_modules/figlet/importable-fonts/${name}.js`, import.meta.url);
    const { default: data } = await import(modPath);
    figlet.parseFont(name, data);
    const lines = trimRows(figlet.textSync(ALPHA, { font: name, width: 100000, whitespaceBreak: false }));
    const cols = Math.max(...lines.map((l) => [...l].length));
    const size = statSync(modPath).size;
    total += size;
    imports.push(`import ${ident(name)} from 'figlet/fonts/${name}';`);
    entries.push(`  ${JSON.stringify(name)}: { data: ${ident(name)}, family: '${family}', blessed: ${BLESSED.has(name)}, rows: ${lines.length}, perLetter: ${(cols / 26).toFixed(1)} },`);
    console.log(`${name.padEnd(22)} ${family.padEnd(10)} rows ${String(lines.length).padStart(2)}  per letter ${(cols / 26).toFixed(1).padStart(5)}  ${(size / 1024).toFixed(0).padStart(4)} KB`);
  }
}
const src = `// Generated by tools/embed-fonts.mjs from figlet ${JSON.parse(await import('node:fs').then((fs) => fs.readFileSync(new URL('../../../node_modules/figlet/package.json', import.meta.url), 'utf8'))).version}. Do not edit; edit the tool and rerun it.
// Each entry: the font's FLF text, its family, whether it is blessed, its row count, and its columns per capital letter (the alphabet's width over 26).
${imports.join('\n')}

export const FONTS = {
${entries.join('\n')}
};
`;
writeFileSync(new URL('../fonts.js', import.meta.url), src);
console.log(`\n${entries.length} fonts, ${(total / 1024).toFixed(0)} KB of font modules`);
